name: Deploy Shopco to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/kiyim
            git fetch --all
            git restore backend/database.sqlite
            git reset --hard origin/main
            npm install
            cd frontend
            npm install
            npm run build
            cd ..
            pm2 restart shopco || pm2 start backend/server.js --name shopco
            pm2 save
